services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paycore_api
    ports:
      - '3001:3001'
      - '5555:5555'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "pnpm install && pnpm run start:dev"
    environment:
      - CI=true
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: paycore_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: paycore
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: paycore_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
